runtime: nodejs20
env: standard

handlers:
  - url: /.*
    script: auto

service: backend-service

entrypoint: npm run start:prod

env_variables:
  DATABASE_URL: {{DATABASE_URL}}
  SENDGRID_API_KEY: {{SENDGRID_API_KEY}}
  SENDGRID_VERIFIED_SENDER: {{SENDGRID_VERIFIED_SENDER}}
  ENCRYPTION_ROUNDS: {{ENCRYPTION_ROUNDS}}
  JWT_SECRET: {{JWT_SECRET}}