name: Deploy to GCP App Engine

on:
  push:
    branches:
      - master  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install --production

      - name: Build the app
        run: npm run build

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_APP_ENGINE_SERVICE_ACCOUNT }}
          export_default_credentials: true

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_APP_ENGINE_SERVICE_ACCOUNT }}

      # New step to replace environment variables in app.yaml
      - name: Replace environment variables in app.yaml
        run: |
          chmod +x ./replace_env_variables.sh
          ./replace_env_variables.sh
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          SENDGRID_VERIFIED_SENDER: ${{ secrets.SENDGRID_VERIFIED_SENDER }}
          ENCRYPTION_ROUNDS: ${{ secrets.ENCRYPTION_ROUNDS }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}

      - name: Deploy to Google App Engine
        run: |
          gcloud app deploy app.yaml
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
